// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package mysqlsimplecrud

import ()

type Department struct {
	ID   int32
	Name string
}

type Employee struct {
	ID           int32
	Name         string
	DepartmentID int32
}
