// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package mysqlsimplecrud

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateDepartment(ctx context.Context, name string) (sql.Result, error)
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (sql.Result, error)
	DeleteDepartment(ctx context.Context, id int32) (sql.Result, error)
	DeleteEmployee(ctx context.Context, id int32) (sql.Result, error)
	GetAllDepartments(ctx context.Context) ([]Department, error)
	GetAllEmployees(ctx context.Context) ([]GetAllEmployeesRow, error)
	GetDepartment(ctx context.Context, id int32) (Department, error)
	GetDepartmentByName(ctx context.Context, name string) (Department, error)
	GetDepartmentEmployees(ctx context.Context, id int32) ([]Employee, error)
	GetEmployee(ctx context.Context, id int32) (GetEmployeeRow, error)
	UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (sql.Result, error)
	UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
